[package]
name = "netsim"
version = "0.1.0"
edition = "2024"
rust-version = "1.93.1"
license = "Apache-2.0"

[dependencies]
anyhow.workspace = true
netsim-core.workspace = true
thiserror.workspace = true

[dev-dependencies]
clap.workspace = true
rand.workspace = true
